language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.12
      osx_image: xcode7.3
      dotnet: 1.0.0-rc4-0044771

## If `dotnet` configuration doesnt work, use install script instead
# install:
#  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
#  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
#  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  

script:
  - dotnet --info
  # Run a new console app
  - mkdir -p "test/test-dotnet-new" && pushd "test/test-dotnet-new"
  - dotnet new
  - dotnet restore
  - dotnet run a b
  - popd
